In [17]:
#Install Numpy 

In [31]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
#Import Numpy

In [4]:
import numpy as np

In [5]:
a = [1, 2, 3]
type(a)

list

In [11]:
b = np.array([1, 2, 3])
type(b)

numpy.ndarray

In [7]:
print(a)
print(b)

[1, 2, 3]
[1 2 3]


In [12]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
axis=1

In [16]:
np.empty((5, 5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.78148153e-307, 3.44900369e-307],
       [6.23043429e-307, 8.45593934e-307, 7.56593017e-307,
        1.11261027e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306, 7.56599128e-307],
       [1.42417629e-306, 8.45593934e-307, 6.89805151e-307,
        1.60220393e-306, 1.42418172e-306],
       [1.37961641e-306, 1.33508760e-307, 8.45610231e-307,
        2.18568966e-312, 2.12203497e-312]])

In [19]:
np.arange(0, 10, 1) #(start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [24]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [25]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [26]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# ndarray.ndim()
# ndarray.size()
# ndarray.shape()

In [34]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)


[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [36]:
array_example.ndim

3

In [37]:
array_example.size

24

In [38]:
array_example.shape

(3, 2, 4)

In [39]:
arr_one = np.array([[1, 2, 3, 4, 5]])
arr_one.ndim

2

In [40]:
arr_one.size

5

In [41]:
arr_one.shape

(1, 5)

In [44]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [45]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [46]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [47]:
np.newaxis
np.expand_dims

<function numpy.expand_dims(a, axis)>

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [49]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [50]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [51]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [52]:
a = np.array([1, 2, 3, 4, 5,6])
a.shape

(6,)

In [55]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [58]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [59]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [35]:
a = np.array([1, 2, 3])
print(a)
a = np.append(a, 10)
print(a)

[1 2 3]
[ 1  2  3 10]


In [60]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [63]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [64]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [65]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [70]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [80]:
a_1 = np.array([[1, 1],
               [2, 2]])
    
a_2 = np.array([[3, 3],
                [4, 4]])
    
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [81]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [83]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [84]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [88]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [93]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [94]:
b.sum(axis=0)

array([3, 3])

In [95]:
data = np.array([1, 2])
data

array([1, 2])

In [96]:
ones = np.ones(2)
ones

array([1., 1.])

In [97]:
data + ones

array([2., 3.])

In [98]:
data * data

array([1, 4])

In [99]:
data / data

array([1., 1.])

In [100]:
data * 1.6

array([1.6, 3.2])

In [101]:
data * 4

array([4, 8])

In [104]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [105]:
A.sum()

4.8595784

In [106]:
A.min()

0.05093587

In [107]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [108]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [109]:
A.std()

0.21392120766089617

In [114]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.99712172 0.71810595]
 [0.47517003 0.57637831]
 [0.06443424 0.91940021]]


In [115]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [116]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [117]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [118]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [119]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [120]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)


a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [122]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [123]:
data = np.array([[1, 2], [3, 4], [5, 6]])



print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [124]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [125]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [126]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [127]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [128]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [129]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [130]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [134]:
ndarr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])
                  
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [135]:
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [136]:
print(np.zeros((4, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [137]:
print(np.random.random((4, 3, 2)))

[[[0.32408774 0.94255057]
  [0.56050637 0.62717947]
  [0.59004838 0.84779476]]

 [[0.66914553 0.78817642]
  [0.84763555 0.89955001]
  [0.39803477 0.01246757]]

 [[0.7630851  0.75874867]
  [0.72236386 0.85751565]
  [0.45942734 0.95717621]]

 [[0.06737802 0.59786455]
  [0.86108667 0.38390891]
  [0.60266747 0.78523987]]]


In [140]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [141]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])